# SQL: DEBUG
# nodeValue: WARN
# blog: WARN

spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://localhost:3306/banking_application_loans?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC"
    username: ${db_username}
    password: ${db_password}
  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 5MB

  server:
    port: 8081

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true

# logging:
#   level:
#     org:
#       springframework:
#         security: DEBUG